import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import type { FastifyInstance } from "fastify";
import { buildApp } from "../../../app.js";
import type { FutureDebtService } from "../future.service.js";

describe("DELETE /api/future-debt/rows/:id — production UUID contract", () => {
  let app: FastifyInstance;
  const deleteProjectionRow = vi.fn(async (_id: string) => undefined);

  beforeAll(async () => {
    const service = {
      deleteProjectionRow,
    } as unknown as FutureDebtService;

    app = await buildApp({ futureDebtService: service });
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
  });

  it("accepts UUID IDs generated by CardInstallmentProjection @default(uuid())", async () => {
    const projectionId = "550e8400-e29b-41d4-a716-446655440000";

    const response = await app.inject({
      method: "DELETE",
      url: `/api/future-debt/rows/${projectionId}`,
    });

    expect(response.statusCode).toBe(204);
    expect(deleteProjectionRow).toHaveBeenCalledWith(projectionId);
  });

  it("keeps malformed IDs rejected with 400", async () => {
    const response = await app.inject({
      method: "DELETE",
      url: "/api/future-debt/rows/not-an-id",
    });

    expect(response.statusCode).toBe(400);
    expect(JSON.parse(response.body)).toMatchObject({ code: "INVALID_ID" });
  });
});
